### ISSUE TITLE
Make Linux Build

### ISSUE THREAD

**Issue by muratunver** [USNavalResearchLaboratory/nrlsmf#1]
Hello,

I try to make file Linux Binaries, but i am getting following errors:

make: Nothing to be done for 'Makefile.linux'.
make: *** No rule to make target 'nrlsmf'.  Stop.

I am using Ubuntu 20.04 LTS and installed protolib

**Comment by bebopagogo** [comment]
Do the following steps work?

git clone https://github.com/USNavalResearchLaboratory/nrlsmf.git
cd nrlsmf
git clone https://github.com/USNavalResearchLaboratory/protolib.git
cd ../makefiles
make -f Makefile.linux nrlsmf

The above steps checkout the latest version of the nrlsmf code and place a copy of the protolib source tree in the proper location (I plan to make protolib a git submodule for nrlsmf at some point).  My Ubuntu system is 16.04 and I am able to build it without issue this way.

**Comment by b00ga** [comment]
Confirmed
```
vagrant@vagrant:~/nrlsmf/makefiles$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
Similar steps:
```
sudo apt install -y g++ libnetfilter-queue-dev
git clone https://github.com/USNavalResearchLaboratory/nrlsmf
cd nrlsmf
git clone https://github.com/USNavalResearchLaboratory/protolib
cd makefiles
make -f Makefile.linux
```
produced:
```
vagrant@vagrant:~/nrlsmf/makefiles$ ls -l nrlsmf 
-rwxrwxr-x 1 vagrant vagrant 3324864 May 23 01:21 nrlsmf
```

**Comment by 1328720068** [comment]
75/5000
[翻译](javascript:;)
Ubuntu 20.04 LTS
core 8.2.0
How can I run the nrlsmf service in the core network simulation platform after I build the nrlsmf
