### ISSUE TITLE
 nhdp binary compile errors

### ISSUE THREAD

**Issue by oytunyapar** [USNavalResearchLaboratory/nrlsmf#2]
branch: master
commit:427df3d1063be84553b0c548c1b629606dd829be

nhdp.h
    Line 116:    class AddressAssociation// ;

nhdpTest.cpp
    Line 236:    char* ptr = strchr(val, '/'); // char* ptr -> const char* ptr

**Comment by bebopagogo** [comment]
The nhdp code included in the nrlsmf tree is a "starter" code stub that was not completed.   We have subsequently implemented NHDP at NRL as part of our OLSRv2 implementation but public release of that implementation is still pending.
