### ISSUE TITLE
Specific Build Instructions Not Available

### ISSUE THREAD

**Issue by ffu** [USNavalResearchLaboratory/nrlsmf#7]
Building nrlsmf and linking to protolib is vague. Please provide specific instructions to do so. Here is how our team did it, but we are not sure if this is correct:

1. Clone the nrlsmf repository
2. cd nrlsmf
3. Clone the protolib repository
4. cd makefiles
5. make -f Makefile.\<platform\>, e.g. "make -f Makefile.linux"
6. **Observe error:** "../src/linux/linuxDetour.cpp:13:51: fatal error: libnetfilter-queue/libnetfilter_queue.h: No such file or directory"
7. Install libnetfilter-queue. For Ubuntu, this is "sudo apt install libnetfilter-queue-dev"
8. Repeat step 5
9. If desired install: "sudo cp nrlsmf /usr/local/bin"

**Comment by weston-nrl** [comment]
That is correct.
