### ISSUE TITLE
Invoke the nrl service in core

### ISSUE THREAD

**Issue by 1328720068** [USNavalResearchLaboratory/nrlsmf#9]
Ubuntu 20.04 LTS
core 8.2.0
How can I run the nrlsmf service in the core network simulation platform after I build the nrlsmf

**Comment by 1328720068** [comment]
hello
Also want to know if I use nrlsmf in the core platform, make -f Makefile.linux or make -f Makefile.core at build time command

**Comment by 1328720068** [comment]
I built the nrlsmf file in the makefiles folder of nrlsmf, but failed to find it when executing the nrlsmf startup command: nrlsmf

**Comment by weston-nrl** [comment]
Copy or symlink the nrlsmf executable you built in the makefiles folder to somewhere in your PATH, e.g. /usr/local/bin.

**Comment by 1328720068** [comment]
Thank you. That solved my problem
